# Generated by Django 2.2 on 2021-03-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_prolefeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProleFeedItem',
            new_name='ProfileFeedItem',
        ),
    ]
